### ISSUE TITLE
kernel die after cv2.imshow

### ISSUE THREAD

**Issue by scotthuang1989** [mrever/CASIS-OpenCV-Course#1]
Hi I  originally open the question at stackoverflow [link](https://stackoverflow.com/questions/46236180/opencv-imshow-will-cause-jupyter-notebook-crash?noredirect=1#comment79438466_46236180), I can't find the solution for 2 days. but I saw you code run perfectly in your video. can you give me some advice?

**Comment by mrever** [comment]
Hi Scott,

Unfortunately, I cannot reproduce your error.  I am running on Windows
64-bit, but with either Python 3.5/3.6, OpenCV 3.1/3.2, it works fine for
me (I can create and close the image window with no issues).  So it may be
something that works on Windows but not Ubuntu.

I would agree with what the commenter wrote on stackoverflow--you generally
don't want to create new windows within a Jupyter notebook.  I demonstrated
that in my course mainly to show the difference between numpy and cv2's
image handling methods (particulary RGB vs BGR color schemes), but I
generally would use something like

%pylab notebook
im2disp = imread('data/home.jpg')
figure(); imshow(im2disp)

and have the image displayed in the notebook.  You can use cv2 to operate
on the image just the same using numpy's imread method.

Hope this helps,
-Matt

**Comment by mrever** [comment]
Small correction--imread is within matplotlib.pyplot, not numpy.

**Comment by scotthuang1989** [comment]
ok. I will write code in script for now. I don't want setup a environment  on windows. thanks for your help.
